version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=achat_db
    volumes:
      - db:/var/lib/mysql
  app-achat:
    depends_on:
      - mysqldb
    image : seif717/achat:1.0.0
    restart: on-failure
    ports:
      - 8082:8082
    environment : 
      SPRING_APPLICATION_JSON : '{
        "spring.datasource.url" : "jdbc:mysql://localhost:3306/achat_db?createDatabaseIfNotExist=true" , 
        "spring.datasource.username" : "root" ,
        "spring.datasource.password": null , 
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect" ,
        "spring.jpa.hibernate.ddl-auto" : "update"
      }' 
    stdin_open: true
    tty: true
volumes:
  db: